//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM_IPS.RGRLLCAMSProyectoMDD
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "RGRLLCAMSProyectoMDD";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"RGRLLCAMSProyectoMDD";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID RGRLLCAMSProyectoMDDDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(RGRLLCAMSProyectoMDDCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID RGRLLCAMSProyectoMDDExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(RGRLLCAMSProyectoMDDCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewRGRLLCAMSProyectoMDDExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(RGRLLCAMSProyectoMDDCommandSetId), 0x0001);
	
		// Package identifier
		public const string RGRLLCAMSProyectoMDDPackageId = "44324b7a-2a25-43bd-ad2e-364d605787ae";
		
		// Editor factory identifier
		public const string RGRLLCAMSProyectoMDDEditorFactoryId = "88636354-3665-4119-8c25-e47fcd1909c5";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string RGRLLCAMSProyectoMDDModelExplorerToolWindowId = "6b57b3c7-1236-4bc2-939f-bc5b841ef1b2";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UPM_IPS.RGRLLCAMSProyectoMDD
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string RGRLLCAMSProyectoMDDCommandSetId = "f7fef914-1f3d-403a-ad8b-72de15c61e70";
	}
}